### PR TITLE
Adding conan for dependency management

### PR DESCRIPTION
**Pull request by Yuhanun**

### CODE REVIEW

**Comment by rolfvdhulst** [comment]
I had some troubles building related to libraries which often end with 'libxcb-...-'

Had to install the following packages using apt before I got things working on my version (Ubuntu 22.04 Jammy Jelllyfish)

libx11-xcb-dev
libxaw7-dev
libfontenc-dev
libxcomposite-dev
libxdamage-dev
libxkbfile-dev
libxmuu-dev  
libxres-dev
libxtst-dev
libxvmc-dev
libxcb-render0-dev
libxcb-render-util0-dev
libxcb-xkb-dev
libxcb-icccm4-dev
libxcb-image0-dev 
libxcb-keysyms1-dev
libxcb-randr0-dev
libxcb-shape0-dev
libxcb-sync-dev
libxcb-xfixes0-dev
libxcb-xinerama0-dev
libxcb-dri3-dev
libxcb-util-dev
libxcb-util0-dev

Any idea why we need these now according to conan but not before?
Also, just a warning for others; first time running conan gives quite long build times (beware...). It seems like it's building QT5 for me separately again, even though I have it installed? My PC actually crashed running conan for the first time...

**Comment by rolfvdhulst** [comment]
Ok, seems to build/run fine for me now

**Comment by rolfvdhulst** [comment]
Nvm, I still have issues building roboteam_robothub.
There are some failing tests, in roboteam_ai, but it seems that this is not due to conan. 

I also get the following warnings with QT, although the QT applications run:

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Fontconfig error: Cannot load default config file: No such file: (null)

And the fonts indeed look a bit scuffed.

**Comment by rolfvdhulst** [comment]
Font issues are fixed by adding 'FONTCONFIG_PATH=/etc/fonts/' to my environmental variables in CLion

**Comment by Yuhanun** [comment]
Didnt' have any issues running, didn't run tests, kinda assumed they ran in CI.

Wondering if you're on xorg or wayland?

**Comment by Yuhanun** [comment]
I had issues building roboteam_robothub because of proto stuff, what are the issues you have?

**Comment by rolfvdhulst** [comment]
I'm on wayland. When trying to build roboteam_robothub, I get the following. It seems the proto compiler is trying to run on files which do not exist?
```
[60/104] Running cpp protocol buffer compiler on /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto/proto/ssl_simulation_control.proto
FAILED: roboteam_robothub/simulation_proto/proto/ssl_simulation_control.pb.h roboteam_robothub/simulation_proto/proto/ssl_simulation_control.pb.cc /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto/proto/ssl_simulation_control.pb.h /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto/proto/ssl_simulation_control.pb.cc 
cd /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto && /usr/local/bin/protoc --cpp_out :/home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto -I /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto/proto/ssl_simulation_control.proto
ssl_gc_common.proto: File not found.
ssl_simulation_config.proto: File not found.
ssl_simulation_error.proto: File not found.
proto/ssl_simulation_control.proto:6:1: Import "ssl_gc_common.proto" was not found or had errors.
proto/ssl_simulation_control.proto:7:1: Import "ssl_simulation_config.proto" was not found or had errors.
proto/ssl_simulation_control.proto:8:1: Import "ssl_simulation_error.proto" was not found or had errors.
proto/ssl_simulation_control.proto:42:14: "RobotId" is not defined.
proto/ssl_simulation_control.proto:85:14: "SimulatorConfig" is not defined.
proto/ssl_simulation_control.proto:91:14: "SimulatorError" is not defined.
[61/104] Running cpp protocol buffer compiler on /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto/proto/ssl_simulation_config.proto
FAILED: roboteam_robothub/simulation_proto/proto/ssl_simulation_config.pb.h roboteam_robothub/simulation_proto/proto/ssl_simulation_config.pb.cc /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto/proto/ssl_simulation_config.pb.h /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto/proto/ssl_simulation_config.pb.cc 
cd /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto && /usr/local/bin/protoc --cpp_out :/home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto -I /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto/proto/ssl_simulation_config.proto
ssl_gc_common.proto: File not found.
ssl_vision_geometry.proto: File not found.
proto/ssl_simulation_config.proto:6:1: Import "ssl_gc_common.proto" was not found or had errors.
proto/ssl_simulation_config.proto:7:1: Import "ssl_vision_geometry.proto" was not found or had errors.
proto/ssl_simulation_config.proto:43:14: "RobotId" is not defined.
proto/ssl_simulation_config.proto:72:14: "SSL_GeometryData" is not defined.
[62/104] Running cpp protocol buffer compiler on /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto/proto/ssl_simulation_robot_feedback.proto
FAILED: roboteam_robothub/simulation_proto/proto/ssl_simulation_robot_feedback.pb.h roboteam_robothub/simulation_proto/proto/ssl_simulation_robot_feedback.pb.cc /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto/proto/ssl_simulation_robot_feedback.pb.h /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto/proto/ssl_simulation_robot_feedback.pb.cc 
cd /home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto && /usr/local/bin/protoc --cpp_out :/home/rolf/roboteam/roboteam/cmake-build-debug/roboteam_robothub/simulation_proto -I /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto /home/rolf/roboteam/roboteam/roboteam_robothub/simulation_proto/proto/ssl_simulation_robot_feedback.proto
ssl_simulation_error.proto: File not found.
proto/ssl_simulation_robot_feedback.proto:6:1: Import "ssl_simulation_error.proto" was not found or had errors.
proto/ssl_simulation_robot_feedback.proto:22:14: "SimulatorError" is not defined.
[66/104] Building CXX object roboteam_networking/proto/CMakeFiles/roboteam_networking_proto.dir/messages_robocup_ssl_game_event.pb.cc.o
ninja: build stopped: subcommand failed.

```

**Comment by rolfvdhulst** [comment]
@Yuhanun Check if the changes I did fixed it for you; It did fix for me, at least.

**Comment by rolfvdhulst** [comment]
So what is the status of this branch? Can we merge it, or does conan still not work?

**Comment by YuhanunCitgez** [comment]
> So what is the status of this branch? Can we merge it, or does conan still not work?

Haven't been able to work on it for a while due to a new job. I'll try take a look soon but can't promise anything.

**Pull request closed without merging**
