### PR TITLE
[roboteam_ai] Improve workflow with new docker structure

### PR DESCRIPTION
**Pull request by tollsimy**
Improve workflow with new docker structure, see `docker/README.md`

### CODE REVIEW

**Comment by JornJorn** [comment]
Very nice :+1: , this will for sure make life a bit easier (software installation speedrun next transfer moment)

I would add the installation to the readme as well (https://docs.docker.com/engine/install/ or https://docs.docker.com/engine/install/ubuntu/ and https://docs.docker.com/engine/install/linux-postinstall/)

And the typo in the readme, docker compose instead of docker-compose

In the game docker there still is secondary ai and autoref which we don't need during a game/demo

**Comment by tollsimy** [comment]
Fixed

**Comment by emielsteerneman** [comment]
I'm not entirely convinced by this PR. Please correct me if I'm wrong

* It seems like we lose the ability to simply pull the image and run our software. 
* Is the only difference between the `Development` target and the `Release` target now that the `Release` target comes without the source for protobuf?

The Dockerfile was initially written with the intent of having the `Development` target as one that could be pulled and hooked into with e.g. VSCode, and the `Release` target as a small as possible image for simple deployment, also for Windows machines. It seems that it has lost this structure, which is not bad per se, but I don't fully understand what is gained with this PR

**Comment by tollsimy** [comment]
> I'm not entirely convinced by this PR. Please correct me if I'm wrong
> 
>     * It seems like we lose the ability to simply pull the image and run our software.
> 
>     * Is the only difference between the `Development` target and the `Release` target now that the `Release` target comes without the source for protobuf?
> 
> 
> The Dockerfile was initially written with the intent of having the `Development` target as one that could be pulled and hooked into with e.g. VSCode, and the `Release` target as a small as possible image for simple deployment, also for Windows machines. It seems that it has lost this structure, which is not bad per se, but I don't fully understand what is gained with this PR

We are not loosing any of the previous features, release container is still built and pushed on dockerhub as before (`roboteamtwente/roboteam`).
As you mentioned the difference between `release` and `development` is actually small and it consist mainly on development packages and headers in order to reduce what actually takes more space. The release container takes 875MB, it could be stripped down more but it is not necessary. We are also thinking about releasing self-contained binaries and this could for sure cover that issue in the best way possible.

Answering your second question, what we gain with this PR a definitely faster workflow for development as well as a reliable and reproducible environment that allows developers to build and test with a higher level of abstraction without loosing transparency or loosing the ability to execute manual grunt tasks.
Moreover, the new dockerfile is developed considering the new `simulator` and `game` compose structures that allow to stack multiple services increasing ease of use, isolation, reliability and facilitating integration of different services.

**Review by JornJorn — APPROVED** [review]

**Pull request merged**
