### PR TITLE
Fix compilation error for compatibility with older proto versions

### PR DESCRIPTION
**Pull request by rolfvdhulst**
The function I replaced is only allowed in newer proto versions; Was not compiling with proto 3.12.1 for me.

### CODE REVIEW

**Comment by emielsteerneman** [comment]
So, this takes it back to 3.12.1 compatibility?

**Review by emielsteerneman — APPROVED** [review]
LGTM

**Comment by rolfvdhulst** [comment]
I think so? technically we should be 3.9 compliant since that's what the ReadMe says (or update the readme)

**Comment by emielsteerneman** [comment]
I'm currently updating the README. `install_UBUNTU_22.04.sh` installs Protobuf 3.19.x. roboteam_networking requires version 3.9.1 for some reason.

**Pull request merged**
