### PR TITLE
Fix ai tests linking error

### PR DESCRIPTION
**Pull request by JAndringa**
### Comments for the reviewer
- The ai tests were not linking properly and gave an undefined reference to addDrawing from interface. I put the visualization of path planning in path planning rather than the goToPos skill because that makes more sense. The actual fix was to change the order of the linking libraries. I do not know why this fixes it so if someone does know please tell me.

###### Code Quality
- [x] Is the code is understandable and easy to read
- [x] Changes to the code comply with set clang-format rules
- [x] No use of manual memory control (e.g new/malloc/colloc etc)
- [x] Are (only) smart pointers used?

###### Testing
- [x] All tests are passing.
- [x] I _added new / changed existing_ tests to reflect code changes (state why not otherwise!)
- [x] I tested my changes manually (Describe how, to what extent etc.)

###### Commit Messages
- [x] Commit message is saying what has been changed, **why** it was changed? Remember other developers might not know
  what the problem you are fixing was. Note also negative _decision_ (e.g., why did you not do particular thing)
  **TLDR: Commit message are comprehensive**
- [x] Commit messages follows the rules of https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by emielsteerneman** [comment]
The issue was stuff in the AI code that's currently unused?

**Comment by JAndringa** [comment]
The issue was a combination of the order in which the libraries were linked (second commit) and visualization of the path planning (first commit) which may have not been necessary to move for this specific issue, but it is related and should not be done in the goToPos skill. So it isn't unused

**Comment by emielsteerneman** [comment]
Any idea what change caused the roboteam_ai_tests to suddenly not link anymore? It worked fine for me a week ago

**Review by emielsteerneman — APPROVED** [review]
see comment

**Pull request merged**
