### PR TITLE
Feature/thread safe settings

### PR DESCRIPTION
**Pull request by mamiksik**
### Comments for the reviewer
- 

###### Code Quality
- [x] Is the code is understandable and easy to read
- [x] Changes to the code comply with set clang-format rules
- [x] No use of manual memory control (e.g new/malloc/colloc etc)
- [x] Are (only) smart pointers used?

###### Testing
- [x] All tests are passing.
- [x] I _added new / changed existing_ tests to reflect code changes (state why not otherwise!)
- [ ] I tested my changes manually (Describe how, to what extent etc.)

###### Commit Messages
- [x] Commit message is saying what has been changed, **why** it was changed? Remember other developers might not know
  what the problem you are fixing was. Note also negative _decision_ (e.g., why did you not do particular thing)
  **TLDR: Commit message are comprehensive**
- [x] Commit messages follows the rules of https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by mamiksik** [comment]
@JAndringa All tests are passing! Have a look and merge it if it looks goo to you!:)

**Comment by emielsteerneman** [comment]
I wouldn't mind reviewing this but I have no idea what's going on

**Comment by mamiksik** [comment]
@emielsteerneman I've renamed the settings to GameSettings, removed the unused variables (ergo having vision port as the setting does not make sense, since changing it would require restarting the ZMQ. Just restart the AI) and made them thread-safe.

**Comment by mamiksik** [comment]
Also, there were inconsistencies in using it. Sometimes we would use the global variable SETTINGS and sometimes we would init a local copy.

**Comment by mamiksik** [comment]
Lastly, I created a utility enum RoboHubMode that can be used anywhere in the RTT. Up until now, we had 4 conflicting definitions of RoboHubMode enum.

**Comment by JAndringa** [comment]
I see that you are using a different version of SDL which is giving problems for me. Is there any specific reason for this?

**Review by JAndringa — APPROVED** [review]
LGTM

**Pull request merged**
