### PR TITLE
Added Chipper Code

### PR DESCRIPTION
**Pull request by mirixx**
STP Chipper implementation. Made changes to Controlutils to add ChipForce function and added ChippingPass play to STPManager.

### CODE REVIEW

**Review by JAndringa — CHANGES_REQUESTED** [review]
the chipper itself seems to work but it will only chip a very short distance. did you test it? if yes how? if not please do so. also when determining the chip force, i noticed that one of the limiting factors is TARGET_FACTOR, which is used for shooting at the goal. i don't think we want to use the chipper for this but rather the kicker.

**Comment by alexander-de-ranitz** [comment]
Is it really necessary to have a separate play for a chipping pass? It seems like most of the code is the same as the normal pass. Perhaps it would be sufficient to just add a bit of code to check whether you need to chip or pass normally in the current situation and set the kickType accordingly.

**Comment by JAndringa** [comment]
It's probably not necessary, but it's nice to have consistency. The chipper pass would be used in way different scenarios than a normal pass would.

**Review by JAndringa — APPROVED** [review]
LGTM, very nice finishing touches

**Review by silashoevers — APPROVED** [review]
Robots are properly chipping at accurate enough positions. Looks good to me. Hopefully finetuning can be done with real robots.

**Pull request merged**
